import type { Locale } from "./i18n";
const en = {
  importedFrom: "Reported by", manualDate: "Date set by you", lastPlayed: "Latest known play date", played: "Played", platformDateHelp: "Platform dates appear automatically when available. They confirm activity on those days, not every session between them. Your start-date corrections take priority.",
  monthView: "Month", listView: "List", viewLabel: "Calendar view", today: "Today", selectDay: "Select a day to see its games and dates.", noDayEvents: "No events on this day.", legend: "Event types", moreEvents: "more", estimateReminder: "An estimate, not a deadline.", calendarEmptyHelp: "Record a start date or add a release from the section below.",
  outdated: "This estimate needs an update. Use the daily manual update to recalculate it.",
  title: "Your time with games", body: "Record when you started. Your recent playing pace helps estimate when you may finish.",
  playing: "Following your pace", empty: "Record a start date to begin following a game.", register: "Record a start date", game: "Game", choose: "Choose a game from your library", start: "Started on", save: "Save", edit: "Edit start date", startMissing: "Confirm your start date", finish: "Estimated finish", actualFinish: "Finished", update: "Update estimate", updated: "Last estimate update", notUpdated: "No estimate calculated yet.",
  limit: "Manual update used today", daily: "Updates automatically once a day. You can also update manually once per day. The allowance resets at 00:00 UTC.", data: "Uses the latest synced hours. Sync your sources first if those hours are out of date.",
  learning: "Building your recent history. At least 7 days of observations are needed.", missing_start: "Confirm when you actually started playing. Adding a game to Playing now does not establish its start date.", stale: "Playing time is out of date. Sync your source to resume estimates.", inactive: "No recent progress recorded. The estimate will return when you play again.", correction: "The recorded hours changed source or were corrected. Gathering a new history before estimating.", no_duration: "No main-story duration is available for this game.", ongoing: "This game has no defined ending. No finish date is estimated.", completed: "Completed", paused: "Paused", past_duration: "Your recorded hours exceed the main-story average. That does not mean the game is finished.", ready: "Based on your recent recorded pace; this is an estimate, not a deadline.",
  pace: "h/week in this game", around: "Around", detail: "How this estimate works", method: "Uses changes in this game's recorded hours over up to 28 days, including days off. The remaining main-story duration is divided by that pace. Achievement percentages are not story progress.", session: "Record today's play", minutes: "Minutes played today", sessionHelp: "For games without a connected source. Enter today's total; saving again replaces it, rather than adding it twice.",
  agenda: "Your calendar", previous: "Previous month", next: "Next month", monthNav: "Calendar months", noEvents: "No dates in this month.", began: "Started playing", estimated: "Estimated finish", release: "Release", savedReleases: "Releases you follow", remove: "Remove from calendar", releases: "Release dates", releaseBody: "Daily search across all platforms, using AI and source links. Only release dates appear here.", sources: "Sources", source: "View source", checked: "Checked", add: "Add date to calendar", added: "In your calendar", noDay: "No exact day confirmed", noReleases: "No verified release dates to show yet.", releaseFailed: "The latest release-date search could not finish. Previously found dates may be out of date.", releaseDelayed: "The daily search has not completed recently. Check the source for changes.", changedDate: "Saved releases follow date changes from the same game, platform and region.",
  refreshed: "Estimates updated.", limited: "You have already used today's manual update.", saved: "Saved. Estimate changes appear in the next daily or manual update.", failed: "Could not update estimates. Your daily manual update is still available.", invalid: "Could not save. Check the date or game and try again.", preview: "Read-only preview", loadFailed: "The calendar is unavailable. Please try again later.",
};
const pt: typeof en = {
  importedFrom: "Informado por", manualDate: "Data definida por você", lastPlayed: "Última data de jogo conhecida", played: "Jogou", platformDateHelp: "Datas das plataformas aparecem automaticamente quando disponíveis. Confirmam atividade nesses dias, não todas as sessões entre eles. Suas correções de início têm prioridade.",
  monthView: "Mês", listView: "Lista", viewLabel: "Visualização do calendário", today: "Hoje", selectDay: "Selecione um dia para ver seus jogos e datas.", noDayEvents: "Nenhum evento neste dia.", legend: "Tipos de evento", moreEvents: "mais", estimateReminder: "Uma estimativa, não um prazo.", calendarEmptyHelp: "Registre um início ou adicione um lançamento na seção abaixo.",
  outdated: "Esta estimativa precisa de atualização. Use a atualização manual diária para recalcular.",
  title: "Seu tempo com os jogos", body: "Registre quando começou. Seu ritmo recente ajuda a estimar quando você pode terminar.",
  playing: "Acompanhando seu ritmo", empty: "Registre uma data de início para acompanhar um jogo.", register: "Registrar data de início", game: "Jogo", choose: "Escolha um jogo da sua biblioteca", start: "Comecei em", save: "Salvar", edit: "Editar data de início", startMissing: "Confirme a data de início", finish: "Previsão de término", actualFinish: "Concluído", update: "Atualizar estimativa", updated: "Última atualização das estimativas", notUpdated: "Nenhuma estimativa calculada ainda.",
  limit: "Atualização manual usada hoje", daily: "Atualização automática uma vez por dia. Você também pode atualizar manualmente uma vez por dia. O limite renova à 00h UTC.", data: "Usa as últimas horas sincronizadas. Se estiverem desatualizadas, sincronize suas fontes primeiro.",
  learning: "Montando seu histórico recente. São necessários pelo menos 7 dias de observações.", missing_start: "Confirme quando começou a jogar de fato. Adicionar a Jogando agora não define a data de início.", stale: "As horas jogadas estão desatualizadas. Sincronize a fonte para retomar as estimativas.", inactive: "Sem progresso recente registrado. A estimativa volta quando você jogar novamente.", correction: "As horas registradas mudaram de fonte ou foram corrigidas. Aguardando um novo histórico para estimar.", no_duration: "Ainda não há duração da história principal para este jogo.", ongoing: "Este jogo não tem um final definido. Não há previsão de término.", completed: "Concluído", paused: "Em pausa", past_duration: "Suas horas registradas passaram da duração média da história. Isso não significa que você terminou.", ready: "Baseada no seu ritmo recente registrado. É uma estimativa, não um prazo.",
  pace: "h/semana neste jogo", around: "Por volta de", detail: "Como a estimativa funciona", method: "Usa a variação das horas deste jogo em até 28 dias, incluindo dias sem jogar. Divide o tempo restante da história principal por esse ritmo. Percentuais de conquistas não são progresso na história.", session: "Registrar tempo de hoje", minutes: "Minutos jogados hoje", sessionHelp: "Para jogos sem fonte conectada. Informe o total de hoje; salvar novamente substitui esse valor, sem duplicar as horas.",
  agenda: "Seu calendário", previous: "Mês anterior", next: "Próximo mês", monthNav: "Meses do calendário", noEvents: "Nenhuma data neste mês.", began: "Começou a jogar", estimated: "Término estimado", release: "Lançamento", savedReleases: "Lançamentos que você acompanha", remove: "Remover do calendário", releases: "Datas de lançamento", releaseBody: "Pesquisa diária em todas as plataformas, usando IA e links das fontes. Aqui entram somente datas de lançamento.", sources: "Fontes", source: "Ver fonte", checked: "Verificado em", add: "Adicionar data ao calendário", added: "No seu calendário", noDay: "Sem dia exato confirmado", noReleases: "Nenhuma data de lançamento verificada para mostrar ainda.", releaseFailed: "A última pesquisa de lançamentos não foi concluída. Datas encontradas antes podem estar desatualizadas.", releaseDelayed: "A pesquisa diária não foi concluída recentemente. Confira a fonte para saber se houve mudanças.", changedDate: "As datas salvas acompanham mudanças do mesmo jogo, plataforma e região.",
  refreshed: "Estimativas atualizadas.", limited: "Você já usou a atualização manual de hoje.", saved: "Salvo. Mudanças na estimativa aparecem na próxima atualização diária ou manual.", failed: "Não foi possível atualizar as estimativas. Sua atualização manual diária continua disponível.", invalid: "Não foi possível salvar. Confira a data ou o jogo e tente novamente.", preview: "Prévia somente para leitura", loadFailed: "O calendário está indisponível. Tente novamente mais tarde.",
};
export function calendarCopy(locale: Locale) { return locale === "pt-BR" ? pt : en; }
