import assert from "node:assert/strict";
import { prisma as db } from "../../src/lib/prisma";
import { syncLibraryCopy, upsertLibraryCopy } from "../../src/lib/library-entry";
import { readPlatformEvidence } from "../../src/lib/library-platform-evidence";
import { applyPlatformRepair, capturePlatformRepair, platformRepairHash, validatePlatformRepair } from "../library-platform-repair";

assert.match(new URL(process.env.DATABASE_URL!).searchParams.get("schema") ?? "", /^steam_sync_test_[a-f0-9]{16}$/);
async function main() {
  const user = await db.user.create({ data: { displayName: "Platform provenance fixture" } });
  const other = await db.user.create({ data: { displayName: "Other owner" } });
  const game = await db.game.create({ data: { name: "Platform fixture", normalizedName: "platform fixture", slug: "platform-fixture", platforms: ["Xbox Series X|S", "PC"] } });
  const account = await db.externalAccount.create({ data: { userId: user.id, provider: "STEAM", providerAccountId: "platform-steam" } });
  const psAccount = await db.externalAccount.create({ data: { userId: user.id, provider: "PLAYSTATION", providerAccountId: "platform-ps" } });
  const base = { userId: user.id, gameId: game.id };
  const queued = await upsertLibraryCopy({ ...base, status: "PLAYING_NEXT", explicitStatus: true, create: { source: "MANUAL", playingNextSlot: 1 }, update: {} });
  assert.equal(queued.platformKey, "unknown");
  assert.equal(readPlatformEvidence(queued.rawData)?.source, "unspecified");
  const syncSteam = () => syncLibraryCopy({ ...base, accountId: account.id, provider: "STEAM", source: "STEAM", game: { title: game.name, providerGameId: "100", platformName: "Steam", rawData: { appid: 100 }, playtimeMinutes: 200 } });
  const steam = await syncSteam();
  assert.equal(steam.id, queued.id, "sync adopts the unspecified queue copy");
  assert.equal(steam.status, "PLAYING_NEXT");
  assert.equal(steam.platformName, "Steam");
  assert.equal(readPlatformEvidence(steam.rawData)?.source, "sync");
  assert.equal(readPlatformEvidence(steam.rawData)?.providerGameId, "100");
  const ps = await syncLibraryCopy({ ...base, accountId: psAccount.id, provider: "PLAYSTATION", source: "PLAYSTATION", game: { title: game.name, providerGameId: "title:123", platformName: "PS5" } });
  assert.notEqual(ps.id, steam.id, "two real provider copies remain separate");
  const psRelabeled = await syncLibraryCopy({ ...base, accountId: psAccount.id, provider: "PLAYSTATION", source: "PLAYSTATION", game: { title: game.name, providerGameId: "title:123", platformName: "PS4, PS5" } });
  assert.equal(psRelabeled.id, ps.id, "same provider identity survives a changed platform label");
  const manual = await upsertLibraryCopy({ ...base, platformName: "Nintendo Switch", platformSource: "user", status: "PLAYING_NEXT", create: { source: "MANUAL", platformName: "Nintendo Switch" }, update: {} });
  assert.equal(readPlatformEvidence(manual.rawData)?.source, "user");
  await upsertLibraryCopy({ ...base, status: "PLAYING_NEXT", create: { source: "MANUAL" }, update: {} });
  assert.equal(await db.userGameEntry.count({ where: base }), 3, "unspecified adds never invent another purchase");
  assert.equal(readPlatformEvidence((await db.userGameEntry.findUniqueOrThrow({ where: { id: manual.id } })).rawData)?.source, "user");

  const day = new Date("2026-09-10");
  const duplicate = await db.userGameEntry.create({ data: { ...base, source: "MANUAL", provider: "IGDB", platformName: "Xbox Series X|S", platformKey: "xbox-series", status: "PLAYING_NEXT", isPhysicalCopy: true, isFavorite: true, notes: "My note", playtimeMinutes: 300, playtimeSource: "manual", plannedStartDate: day, rawData: { appid: 100 } } });
  const journal = await db.gameJournalEntry.create({ data: { ...base, userGameEntryId: duplicate.id, source: "manual", externalSourceId: "memory", body: "Keep this" } });
  await db.gameJournalEntry.create({ data: { ...base, userGameEntryId: steam.id, source: "manual", externalSourceId: "memory", body: "Keep both" } });
  const media = await db.journalMedia.create({ data: { journalEntryId: journal.id, kind: "image", url: "/keep.png", storageKey: "keep", mimeType: "image/png" } });
  const review = await db.userGameReview.create({ data: { ...base, userGameEntryId: duplicate.id, body: "Keep review" } });
  await db.calendarSession.createMany({ data: [{ entryId: duplicate.id, day, minutes: 40 }, { entryId: steam.id, day, minutes: 30 }] });
  await db.playObservation.create({ data: { entryId: duplicate.id, day, observedAt: day, totalMinutes: 300, source: "manual" } });
  const isolated = await db.userGameEntry.create({ data: { userId: other.id, gameId: game.id, source: "MANUAL", status: "OWNED", platformKey: "xbox-series" } });
  const plan = { userId: user.id, pairs: [{ duplicateId: duplicate.id, survivorId: steam.id }] };
  let snapshot = await capturePlatformRepair(db, plan);
  validatePlatformRepair(snapshot, plan);
  await db.userGameEntry.update({ where: { id: duplicate.id }, data: { notes: "Updated note" } });
  await assert.rejects(applyPlatformRepair(db, plan, platformRepairHash(snapshot)), /Data changed/);
  snapshot = await capturePlatformRepair(db, plan);
  assert.deepEqual(await applyPlatformRepair(db, plan, platformRepairHash(snapshot)), { merged: 1 });
  const result = await db.userGameEntry.findUniqueOrThrow({ where: { id: steam.id } });
  assert.equal(result.isPhysicalCopy, true);
  assert.equal(result.isFavorite, true);
  assert.equal(result.playtimeMinutes, 300);
  assert.equal(result.playtimeSource, "manual");
  assert.equal(result.notes, "Updated note");
  assert.equal(result.plannedStartDate?.getTime(), day.getTime());
  assert.equal(result.playingNextSlot, 1);
  assert.equal((await db.gameJournalEntry.findUniqueOrThrow({ where: { id: journal.id } })).userGameEntryId, steam.id);
  assert.ok(await db.journalMedia.findUnique({ where: { id: media.id } }));
  assert.equal((await db.userGameReview.findUniqueOrThrow({ where: { id: review.id } })).userGameEntryId, steam.id);
  assert.equal((await db.calendarSession.findUniqueOrThrow({ where: { entryId_day: { entryId: steam.id, day } } })).minutes, 40, "duplicate daily totals are not added together");
  assert.equal((await db.playObservation.findUniqueOrThrow({ where: { entryId_day: { entryId: steam.id, day } } })).totalMinutes, 300);
  assert.deepEqual(await db.userGameEntry.findUniqueOrThrow({ where: { id: isolated.id } }), isolated);
  assert.equal(await db.userGameEntry.count({ where: base }), 3, "legitimate PS and user-selected Switch survive repair");
  snapshot = await capturePlatformRepair(db, plan);
  assert.deepEqual(await applyPlatformRepair(db, plan, platformRepairHash(snapshot)), { merged: 0 });
  await syncSteam();
  assert.equal(await db.userGameEntry.count({ where: base }), 3);
  assert.equal((await db.userGameEntry.findUniqueOrThrow({ where: { id: steam.id } })).playtimeMinutes, 300);
  const ambiguous = await db.userGameEntry.create({ data: { ...base, source: "MANUAL", status: "PLAYING_NEXT", platformName: "Xbox Series X|S", platformKey: "xbox-series", rawData: { appid: 999 } } });
  const unsafe = { userId: user.id, pairs: [{ duplicateId: ambiguous.id, survivorId: steam.id }] };
  assert.throws(() => validatePlatformRepair({ ...snapshot, entries: [...snapshot.entries, ambiguous] }, unsafe), /Ambiguous/);
  const selected = { ...ambiguous, rawData: { appid: 100, libraryPlatformEvidence: { version: 1, source: "user", platformKey: "xbox-series" } } };
  assert.throws(() => validatePlatformRepair({ ...snapshot, entries: [...snapshot.entries, selected] }, unsafe), /separate review/);
  const psGame = await db.game.create({ data: { name: "PS fixture", slug: "ps-provenance-fixture", normalizedName: "ps fixture" } });
  const psRaw = { playStationSyncSources: [{ titleId: "PPSA12345_00", platform: "PS5" }, { npCommunicationId: "NPWR12345_00", trophyTitlePlatform: "PS5" }] };
  const psBase = { userId: user.id, gameId: psGame.id };
  const psReal = await syncLibraryCopy({ ...psBase, accountId: psAccount.id, provider: "PLAYSTATION", source: "PLAYSTATION", game: { title: psGame.name, providerGameId: "title:PPSA12345_00", platformName: "PS5", rawData: psRaw } });
  const psWrong = await db.userGameEntry.create({ data: { ...psBase, status: "OWNED", source: "PLAYSTATION", provider: "PLAYSTATION", platformName: "Xbox Series X|S", platformKey: "xbox-series", rawData: psRaw, isPhysicalCopy: true } });
  const psPlan = { userId: user.id, pairs: [{ duplicateId: psWrong.id, survivorId: psReal.id }] };
  const psSnapshot = await capturePlatformRepair(db, psPlan);
  assert.deepEqual(await applyPlatformRepair(db, psPlan, platformRepairHash(psSnapshot)), { merged: 1 });
  assert.equal((await db.userGameEntry.findUniqueOrThrow({ where: { id: psReal.id } })).isPhysicalCopy, true);
  await upsertLibraryCopy({ ...psBase, platformName: "PS5", platformSource: "user", status: "OWNED", create: { source: "MANUAL" }, update: {} });
  const psConfirmed = await syncLibraryCopy({ ...psBase, accountId: psAccount.id, provider: "PLAYSTATION", source: "PLAYSTATION", game: { title: psGame.name, providerGameId: "title:PPSA12345_00", platformName: "PS5", rawData: psRaw } });
  assert.equal(readPlatformEvidence(psConfirmed.rawData)?.selectedByUser, true, "sync retains evidence of an explicit platform choice");
  console.log("PASS platform provenance, unknown adoption, real multi-platform copies, same-source relabel, guarded repair, status/hours/notes/diary/media/review/calendar preservation, isolation, idempotency, repeat sync and ambiguous/explicit-copy rejection.");
}
main().finally(() => db.$disconnect()).catch(error => { console.error(error); process.exitCode = 1; });
